export const items = [
  {
    id: 1,
    name: "My Hero Academia",
    year:2025,
    genre: "Action-Adventure",
    blurb: "An open world that begs to be explored in every direction.",
    image: "/Hero Academia.jpeg",
    rating: 5,
    emoji: "😎",
  },
  {
    id: 2,
    name: "Attack On Titan",
     year:2026,
    genre:"Dark Fantasy",
    blurb: "A gorgeous, lonely world with combat that feels incredible.",
    image:"/Founding Titan.jpeg",
    rating: 5,
    emoji: "🥷",
  },
  {
    id: 3,
    name: "Jujutsu Kaisen",
    year:2023,
    genre:"Supernatural",
    blurb: "In a world where negative human emotions turn into deadly monsters called Curses, high schooler Yuji Itadori possesses extraordinary strength.",
    image:"/Jujutsu.jpeg",
    rating: 4,
    emoji: "⚔️",
  },
   {
    id: 4,
    name: "Death Note",
    year:2020,
    genre:"Mystery",
    blurb: "It explores dark themes of morality and justice through a suspenseful cat-and-mouse game between a brilliant high school student and a master detective.",
    image:"/Death note.jpeg",
    rating: 5,
    emoji: "👀",
  },
];