export const items = [
  {
    id: 1,
    name: "My Hero Academia",
    year:2016,
    genre: "Action-Adventure",
    blurb: "Superpowers called Quirks are common in society. A powerless boy dreams of becoming a hero. He inherits a legendary power from the top hero. He trains at an elite academy to combat villains.",
    image: "/Hero Academia.jpeg",
    rating: 8,
    emoji: "😎",
  },
  {
    id: 2,
    name: "Attack On Titan",
     year:2013,
    genre:"Dark Fantasy",
    blurb: "Humanity isolates itself inside walled cities to escape man-eating humanoids called Titans. A young boy vows revenge after a Titan destroys his home. He enlists in the military.",
    image:"/Founding Titan.jpeg",
    rating: 9,
    emoji: "🥷",
  },
  {
    id: 3,
    name: "Jujutsu Kaisen",
    year:2020,
    genre:"Supernatural",
    blurb: "In a world where negative human emotions turn into deadly monsters called Curses, high schooler Yuji Itadori possesses extraordinary strength.",
    image:"/Jujutsu.jpeg",
    rating: 5,
    emoji: "⚔️",
  },
   {
    id: 4,
    name: "Death Note",
    year:2006,
    genre:"Mystery",
    blurb: "It explores dark themes of morality and justice through a suspenseful cat-and-mouse game between a brilliant high school student and a master detective.",
    image:"/Death note.jpeg",
    rating: 7,
    emoji: "👀",
  },
  {
    id: 5,
    name: "Black Clover",
    year:2017,
    genre:"Action",
    blurb: " The story features Asta, a boy born with zero magic abilities in a world where magic is everything. It leans heavily into zero-to-hero progression and team-based battles.",
    image:"/Black clover.jpeg",
    rating: 7,
    emoji: "⚔️",
  },
  {
    id: 6,
    name: "Demon Slayer",
    year:2019,
    genre:"Dark fantasy/Martial arts",
    blurb: "Follows Tanjiro Kamado as he trains to become a Demon Slayer to avenge his family and cure his sister. It combines classic martial arts/swordsmanship with grim supernatural elements.",
    image:"/demon slayer.jpeg",
    rating: 9,
    emoji: "⚔️",
  },
  {
    id: 7,
    name: "Gachiakuta",
    year:2025,
    genre:"Dystopian",
    blurb: "Set in a lawless, trash-filled wasteland, it follows a boy named Rudo who gains the power to bring out the soul of discarded items to fight back against a corrupt upper-class society.",
    image:"/gachiakuta.jpeg",
    rating: 7,
    emoji: "👀",
  },
  {
    id: 8,
    name: "Solo Leveling",
    year:2024,
    genre:"Adventure",
    blurb: "Instead of traditional magic, this series relies on a video game system mechanic. Sung Jinwoo, the world's weakest hunter, gains the ability to level up indefinitely, transitioning from an underdog to an overwhelmingly powerful Necromancer/Monarch",
    image:"/Solo Leveling.jpeg",
    rating: 7,
    emoji: "🥷",
  },

{
    id: 9,
    name: "Kaiju no.8",
    year:2024,
    genre:"Adventure",
    blurb: "The story follows Kafka Hibino who, after ingesting a parasitic creature, gains the ability to turn into a kaiju and now must navigate using his power",
    image:"/Kaiju.jpeg",
    rating: 7,
    emoji: "👀",
  },
  {
    id: 10,
    name: "Vinland Saga",
    year:2019,
    genre:"Adventure",
    blurb:"The story follows the life of Thorfinn, who becomes involved with Vikings and war following his father's death at the hands of Askeladd.",
    image:"/Vinland.jpeg",
    rating: 4,
    emoji: "⚜️",
  },
];